### ISSUE TITLE
Request for the github.com/robopen 

### ISSUE THREAD

**Issue by vikashplus** [mat-kud/ui_tests_selenium#1]
Hi,

We have a project called robopen that we have been working on for the past 3 years. We want to release the project on the link "https://robopen.github.io/".  This domain is currently occupied by your organization name github.com/robopen. We wanted to reach out to check if this name is critical to you. We would be incredibly grateful if you have the flexibility to change the name so that we can release our project using https://robopen.github.io/ 

Forever grateful for your consideration on this matter. 
Best
Vikash

**Comment by mat-kud** [comment]
Hello,
I have just changed my account's name, so you are free to use the "RoboPen"
name. Good luck with your project.

wt., 11 lip 2023 o 03:06 Vikash Kumar ***@***.***> napisał(a):

**Comment by vikashplus** [comment]
Omg, thank you for your generosity.
Hope we will be able to pay it forward.
Best,
Vikash
